### ISSUE TITLE
Issue with zipcode data

### ISSUE THREAD

**Issue by sheilagithub** [Azure-Samples/search-dotnet-asp-net-mvc-jobs#4]
I'm receiving an error when trying to import your zipcode data:  

The request is invalid. Details: actions : 0: The data field 'geo_location' has an invalid latitude coordinate -117.8123. A latitude coordinate must be a value between -90.0 and +90.0 degrees.\r\n1: 

It appears the edm.GeographyPoint models literals as longitude:latitude, versus the standard latitude:longitude.  Is there any way these numbers are entered backwards in your json files?

https://msdn.microsoft.com/en-us/library/dd541295.aspx

**Comment by bitsforthought** [comment]
@sheilagithub Yes, it's possible. There used to be a bug in Azure Search where we would accept co-ordinates with out-of-range values, but we fixed it a while ago. The data for this sample might predate that bug fix.

I'll make sure the sample data gets fixed.

**Comment by sheilagithub** [comment]
I ran a regex replace on the json files (see attached file)

**Comment by liamca** [comment]
I have added a sample that loads both the ZipCodes and Jobs data into Azure Search indexes.  This can be [found here](https://github.com/Azure-Samples/search-dotnet-asp-net-mvc-jobs/tree/master/DataLoader).  Please note that I also updated the zipcodes data files so that the lat / lon are in the correct order.
